### PR TITLE
Better lists

### PR DESCRIPTION
**Pull request by logancostello**
Create the listItem component, which is a single item in a list. It has the index, an image, and the name

I made the home page and the sharing page use this component in their lists to make them look better.

These pages also strictly enforce that the three sections are the same size. The text inside the sections grows as far as it can, but then it gets truncated if its too long.

### CODE REVIEW

**Comment by logancostello** [comment]
PNG image

This is what the new lists look like. You can see that the text fills fully the gets cut off if needed.

**Review by akrimer — APPROVED** [review]
i really like this feature, I think have both the url availbe to comment out is necessary for us to build efficiently. 
the ListItem function looks spotless and like its going to work really well with the rest of our features. i see you have full integrated it into our packages and it is ready to be deployed. 

LGTM!!!

**Review by nathanlim1 — CHANGES_REQUESTED** [review]
Looks fantastic! We can finally compete with Spotify Wrapped. The only thing is that the generate png seems to be broken. We should fix that before we merge the branch.

**Comment by logancostello** [comment]
Thats for the feedback guys! Just fixed the download feature. Should be good to go now!

**Review by luke-villaluz — APPROVED** [review]
love the changes, look sick

**Pull request merged**
